### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by siggi85** [t4qjXH8N/ioBroker.google-sharedlocations#20]
Habe korrekte Logindaten eingetragen, Adapter verbindet sich aber nicht.
Laut ioBroker-Forum ist das ein bekanntes Problem, wenn man bisher noch nicht eingeloggt war. Da ich kein issue hierzu gefunden habe, dachte ich mach ich mal eins auf.
Würde mich freuen den Adapter in Zukunft nutzen zu können. :)

**Comment by siggi85** [comment]
Is it planned to fix the "connection failed issue"? Ireally want to use this adapter. :)

**Comment by t4qjXH8N** [comment]
I am going to release an update during next week.

**Comment by siggi85** [comment]
Wonderful. :)

**Comment by FlexerJR** [comment]
Hallo ich hab ein ähnliches Problem. Hier einmal das Log


google-sharedlocations.0 | 2019-03-06 11:18:27.774 | debug | system.adapter.admin.0: logging true
-- | -- | -- | --
google-sharedlocations.0 | 2019-03-06 11:18:26.143 | debug | system.adapter.admin.0: logging false
google-sharedlocations.0 | 2019-03-06 11:18:24.453 | debug | stateChange google-sharedlocations.0.info.connection  {"val":false,"ack":false,"ts":1551867504449,"q":0,"from":"system.adapter.google-sharedlocations.0","lc":1551865618097}
google-sharedlocations.0 | 2019-03-06 11:18:24.448 | error | First connection failed.
google-sharedlocations.0 | 2019-03-06 11:18:24.448 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
google-sharedlocations.0 | 2019-03-06 11:18:24.448 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
google-sharedlocations.0 | 2019-03-06 11:18:24.446 | debug | [google auth] connectEnterVerificationEmail
google-sharedlocations.0 | 2019-03-06 11:18:24.311 | debug | [google auth] Connection third stage additional verification needed.
google-sharedlocations.0 | 2019-03-06 11:18:24.196 | debug | [google auth] Connection third stage
google-sharedlocations.0 | 2019-03-06 11:18:24.195 | debug | [google auth] Connection second stage successful
google-sharedlocations.0 | 2019-03-06 11:18:23.864 | debug | [google auth] Connection second State
google-sharedlocations.0 | 2019-03-06 11:18:23.863 | debug | [google auth] Connection first stage successfull
google-sharedlocations.0 | 2019-03-06 11:18:23.420 | debug | [google auth] Connection First State
google-sharedlocations.0 | 2019-03-06 11:18:23.418 | info | Starting google shared locations adapter
google-sharedlocations.0 | 2019-03-06 11:18:23.416 | info | starting. Version 1.5.2 in /opt/iobroker/node_modules/iobroker.google-sharedlocations, node: v8.14.0
google-sharedlocations.0 | 2019-03-06 11:18:23.297 | debug | statesDB connected
google-sharedlocations.0 | 2019-03-06 11:18:23.266 | debug | objectDB connected
google-sharedlocations.0 | 2019-03-06 11:18:20.282 | debug | [google auth] Connection logout.
google-sharedlocations.0 | 2019-03-06 11:18:19.778 | info | cleaned everything up...
google-sharedlocations.0 | 2019-03-06 11:18:19.777 | debug | [google auth] Connection logout.


google-sharedlocations.0 | 2019-03-06 11:21:22.050 | debug | stateChange  google-sharedlocations.0.info.connection  {"val":false,"ack":false,"ts":1551867682045,"q":0,"from":"system.adapter.google-sharedlocations.0","lc":1551865618097}
-- | -- | -- | --
google-sharedlocations.0 | 2019-03-06 11:21:22.046 | error | First connection failed.
google-sharedlocations.0 | 2019-03-06 11:21:22.046 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
google-sharedlocations.0 | 2019-03-06 11:21:22.046 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
google-sharedlocations.0 | 2019-03-06 11:21:22.046 | debug | [google auth] connectEnterVerificationEmail
google-sharedlocations.0 | 2019-03-06 11:21:21.907 | debug | [google auth] Connection third stage additional verification needed.
google-sharedlocations.0 | 2019-03-06 11:21:21.795 | debug | [google auth] Connection third stage
google-sharedlocations.0 | 2019-03-06 11:21:21.794 | debug | [google auth] Connection second stage successful
google-sharedlocations.0 | 2019-03-06 11:21:21.579 | debug | [google auth] Connection second State
google-sharedlocations.0 | 2019-03-06 11:21:21.579 | debug | [google auth] Connection first stage successfull
google-sharedlocations.0 | 2019-03-06 11:21:21.135 | debug | [google auth] Connection First State
google-sharedlocations.0 | 2019-03-06 11:21:21.135 | info | Starting google shared locations adapter
google-sharedlocations.0 | 2019-03-06 11:21:21.135 | info | starting. Version 1.5.2 in /opt/iobroker/node_modules/iobroker.google-sharedlocations, node: v8.14.0
google-sharedlocations.0 | 2019-03-06 11:21:17.891 | debug | [google auth] Connection logout.
google-sharedlocations.0 | 2019-03-06 11:21:17.388 | info | cleaned everything up...
google-sharedlocations.0 | 2019-03-06 11:21:17.388 | debug | [google auth] Connection logout.
google-sharedlocations.0 | 2019-03-06 11:20:53.313 | debug | system.adapter.admin.0: logging true
google-sharedlocations.0 | 2019-03-06 11:20:48.982 | debug | sendTo "checkConnection" to system.adapter.admin.0 from system.adapter.google-sharedlocations.0: false
google-sharedlocations.0 | 2019-03-06 11:20:48.981 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
google-sharedlocations.0 | 2019-03-06 11:20:48.981 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
google-sharedlocations.0 | 2019-03-06 11:20:48.980 | debug | [google auth] connectEnterVerificationEmail
google-sharedlocations.0 | 2019-03-06 11:20:48.830 | debug | [google auth] Connection third stage additional verification needed.
google-sharedlocations.0 | 2019-03-06 11:20:48.715 | debug | [google auth] Connection third stage
google-sharedlocations.0 | 2019-03-06 11:20:48.714 | debug | [google auth] Connection second stage successful
google-sharedlocations.0 | 2019-03-06 11:20:48.433 | debug | [google auth] Connection second State
google-sharedlocations.0 | 2019-03-06 11:20:48.432 | debug | [google auth] Connection first stage successfull
google-sharedlocations.0 | 2019-03-06 11:20:48.062 | debug | [google auth] Connection First State

**Comment by siggi85** [comment]
It is still not working. :(

**Comment by t4qjXH8N** [comment]
Google erlaubt keine Logins mehr ohne Javascript. Ohne Update des Adapters wird das nichts.

**Comment by Garfonso** [comment]
Hi,
ich bin auf den Adapter gestoßen und habe mal bei anderen gestöbert. Home Assistant Google Location Sharing geht. Da muss man die [Cookies aus dem Webbrowser in einer Textdatei speichern](https://www.home-assistant.io/integrations/google_maps/). Hab die python library dahinter ausprobiert -> geht auf der Kommandozeile. 

Ein ähnliches Konzept verfolgt ja auch der alexa2 Adapter, da macht der Adapter einen Proxy auf, über den man sich bei Amazon einloggen muss und speichert sich dabei das Cookie (und wohl heute noch viel mehr, so dass vieles automatisch geht).

Sowas sollte also hier auch möglich sein. 
Ich würde mir mal angucken, ob ich einen Pull Request hinbekomme (hauptsächlich Zeit Problem), wollte aber vorher hier kurz posten, um zu gucken, ob @t4qjXH8N überhaupt noch aktiv ist und sich den angucken würde. 

Besteht bei @t4qjXH8N also noch Interesse den Adapter wieder zu beleben?

Viele Grüße,
Achim

**Comment by t4qjXH8N** [comment]
Hallo Achim, 

vielen Dank für deine Hinweise. Die Methode mit dem Cookie ist mir bekannt. Ich habe vor einiger Zeit begonnen einen Proxy wie beim Alexa-Adapter hinzuzufügen. Mein letzter Stand ist im Branch "proxy".

Ich muss aber leider zugegeben, dass ich es zeitlich nicht mehr schaffen werde, die Entwicklung des Adapters weiterzuführen. Vielleicht hat die Community Zeit und Lust weiterzumachen?

**Comment by Garfonso** [comment]
Hi,
der große Vorteil der Organisation "iobroker-community-adapters" ist, dass dort mehrere Leute Rechte haben und auch npm Pakete publishen können und so dann auch releases machen, wenn der Hauptmaintainer mal nicht reagieren kann.
Grundsätzlich könnte ich mir schon vorstellen die Pflege zu übernehmen. 

Viele Grüße,
Achim

**Comment by Garfonso** [comment]
Also, wenn du deinen Adapter in die Community überführen willst, ist hier der Weg beschrieben, was du dafür tun musst: https://github.com/iobroker-community-adapters/info
